import os
import logging
from datetime import datetime
from typing import List, Optional
from utils.config_loader import load_config

logger = logging.getLogger(__name__)


def export_report(
    report_text: str,
    companies: List[str],
    directory: Optional[str] = None,
) -> str:
    """
    Export the final intelligence report as a timestamped Markdown file.

    BUG FIX: In the original codebase this function was defined but never called —
    reports were discarded after each pipeline run. Now called from main.py after
    every successful graph execution.

    Returns the filepath of the saved report.
    """
    config = load_config()
    directory = directory or config["analysis"]["output_dir"]
    os.makedirs(directory, exist_ok=True)

    timestamp    = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    date_display = datetime.now().strftime("%Y-%m-%d at %H:%M UTC")
    company_list = ", ".join(companies)
    filename     = f"{directory}/hiresignal_{timestamp}.md"

    markdown = f"""# 🧠 HireSignal — AI Hiring Intelligence Report

**Generated:** {date_display}
**Companies Analyzed:** {company_list}
**Powered by:** HireSignal — Agentic Intelligence Pipeline

---

{report_text}

---

*This report was generated by an autonomous multi-agent pipeline using real-time job posting and news data.
Signals are indicative, not definitive. Verify before making strategic decisions.*
"""

    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown)
        logger.info(f"Report saved: {filename}")
        return filename
    except Exception as e:
        logger.error(f"Failed to save report: {e}")
        raise
